apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio-modernization-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: portfolio-modernization

configMapGenerator:
  - name: portfolio-config
    behavior: merge
    literals:
      - db.host=postgres-dev-service
      - db.name=portfolio_dev

secretGenerator:
  - name: portfolio-secrets
    literals:
      - db.username=portfolio_dev
      - db.password=dev_password_change_me
