spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clbs
    username: clbs
    password: clbs
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
